# Generated by Django 3.1.7 on 2021-03-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="title",
            new_name="name",
        ),
    ]
