# Generated by Django 3.1.7 on 2021-03-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0003_track_popularity"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="track_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="track",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
    ]
