# Generated by Django 3.1.7 on 2021-03-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0004_auto_20210305_1330"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="track_number",
            new_name="number",
        ),
    ]
