# Generated by Django 3.1.7 on 2021-03-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0006_auto_20210310_2311"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
