# Generated by Django 3.1.7 on 2021-03-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='uri',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='artist',
            table='models_artists',
        ),
    ]
