# Generated by Django 3.1.7 on 2021-03-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0003_auto_20210304_1310"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="uri",
        ),
    ]
