# Generated by Django 3.1.7 on 2021-03-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0004_remove_history_uri"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="history",
            table="history",
        ),
    ]
