name: Push to main branch

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Trigger Jenkins webhook
        env:
          API_KEY: ${{ secrets.JENKINS_API_KEY }}
          USERNAME: ${{ secrets.JENKINS_USERNAME }}
          WEBHOOK_URL: ${{ secrets.JENKINS_WEBHOOK_URL }}
        run: |
          curl -u "$USERNAME:$API_KEY" "$WEBHOOK_URL"

